repos:
  - repo: https://github.com/ambv/black
    rev: '24.4.2'
    hooks:
      - id: black
        args: ['--config=pyproject.toml', '--check', '--diff']
  - repo: https://github.com/PyCQA/flake8
    rev: '5.0.1'
    hooks:
      - id: flake8
        args: ['--config=.flake8']
        additional_dependencies:
          - 'flake8-docstrings==1.6.0'
  - repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
      - id: isort