services:
  server:
    build:
      context: ./  # Set the context to the root of the project
      dockerfile: ./docker/optimization_server/Dockerfile  # Dockerfile location
    ports:
      - "8080:8080"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/optimization_server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
