services:
  server:
    build:
      context: ./  # Set the context to the root of the project
      dockerfile: ./docker/optimization_server/Dockerfile  # Dockerfile location
    ports:
      - "8080:8080"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/optimization_server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server

  # PostgreSQL database service
  db:
    image: postgres:12-20-alpine3.20  # Use the PostgreSQL 12 image
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}  # Name of the database
      POSTGRES_USER: ${POSTGRES_USER_TEST}    # Username for the database
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}  # Password for the database
    ports:
      - "5432:5432"  # Expose the PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

  # Service to populate the database
  query_service:
    build:
      context: ./  # Set the context to the root of the project
      dockerfile: ./docker/query_service/Dockerfile  # Dockerfile location
    depends_on:
      - db  # Ensure the database is ready before running the query service
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER_TEST}:${POSTGRES_PASSWORD_TEST}@db:5432/${POSTGRES_DB_TEST}  # Database connection URL
    volumes:
      - ./query_service:/usr/src/app

# Define a named volume to persist PostgreSQL data
volumes:
  postgres_data: