[package]
name = "rspso"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"]}
rand = "0.8"
ndarray = "0.15.6"
polars = { version = "0.40.0", features = ["lazy", "ndarray", "temporal"] }
lazy_static = "1.4.0"
