version: '3'
services:
  server:
    build: .
    ports:
      - "8080:8080"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
