name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t optimization_server -f docker/optimization_server/Dockerfile .

    - name: Run Docker container
      run: docker run -d -p 8080:8080 optimization_server

    - name: Check health endpoint
      run: |
        sleep 5  # wait for the server to start
        curl --fail http://localhost:8080/health

    - name: Run container tests
      run: |
        pytest tests/integration/test_container.py